### ISSUE TITLE
Spree 4 installation is failing

### ISSUE THREAD

**Issue by creativefurniture** [spree-contrib/spree_editor#151]
After bundle install i am executing 
bundle exec rails g spree_editor:install and i got the response: 
`Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
        48: from bin/rails:4:in `<main>'
        47: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
        46: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        45: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
        44: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        43: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        42: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        41: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        40: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        39: from /usr/local/bundle/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
        38: from /usr/local/bundle/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
        37: from /usr/local/bundle/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
        36: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        35: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        34: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        33: from /usr/local/bundle/gems/railties-6.0.2.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        32: from /usr/local/bundle/gems/railties-6.0.2.2/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        31: from /usr/local/bundle/gems/railties-6.0.2.2/lib/rails/command/actions.rb:22:in `require_application!'
        30: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
        29: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        28: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
        27: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        26: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        25: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        24: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        23: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        22: from /spree/config/application.rb:7:in `<main>'
        21: from /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
        20: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
        19: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
        18: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
        17: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
        16: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
        15: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        14: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        13: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        12: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        11: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        10: from /usr/local/bundle/bundler/gems/spree_editor-58c3634918ab/lib/spree_editor.rb:4:in `<main>'
         9: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
         8: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
         7: from /usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
         6: from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
         5: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
         4: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in `rescue in require'
         3: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         2: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
         1: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- coffee_script (LoadError)`

**Comment by avadhesh82** [comment]
Can you give solution "require': cannot load such file -- coffee_script (LoadError)`"???

**Comment by Tashows** [comment]
> Can you give solution "require': cannot load such file -- coffee_script (LoadError)`"???

You can fork the repository and comment out line 4 (`require 'coffee_script'`) from 
`spree_editor/lib/spree_editor.rb`

I did that and it seemed to work fine.

**Comment by avadhesh82** [comment]
> 
> 
> > Can you give solution "require': cannot load such file -- coffee_script (LoadError)`"???
> 
> You can fork the repository and comment out line 4 (`require 'coffee_script'`) from
> `spree_editor/lib/spree_editor.rb`
> 
> I did that and it seemed to work fine.

you can add this code in gemfile 👍 gem 'spree_editor', github: 'spree-contrib/spree_editor'
gem 'coffee-rails', '~> 5.0.0'
